ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: False
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
    HFOV: 90
    # NOISE_MODEL: "GaussianNoiseModel"  # RGB噪声，在 2020 hc 中不用
    # NOISE_MODEL_KWARGS:
    #   intensity_constant: 0.1
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128
    HFOV: 90
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    # NOISE_MODEL: "RedwoodDepthNoiseModel" # 深度图噪声，在 2020 hc 中不用
  ACTION_SPACE_CONFIG: "pyrobotnoisy"
  NOISE_MODEL:
    ROBOT: 'LoCoBot'
    CONTROLLER: 'ILQR'
    NOISE_MULTIPLIER: 1.0
TASK:
  TYPE: Exp-v0
  POSSIBLE_ACTIONS: ["MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  # GT_EGO_MAP_ANTICIPATED for visualization
  SENSORS: ['NOISY_POSE_SENSOR', 'GT_POSE_SENSOR', 'GT_EGO_MAP_ANTICIPATED', 'COLLISION_SENSOR']
  MEASUREMENTS: ['GT_GLOBAL_MAP', 'TOP_DOWN_MAP_EXP']
  
  # GT_GLOBAL_MAP、GT_EGO_MAP_ANTICIPATED 都是为了可视化
  GT_GLOBAL_MAP:
    MAP_SIZE: 961
    MAP_SCALE: 0.05
    ENVIRONMENT_LAYOUTS_PATH: 'data/datasets/exploration/gibson/v1/val/environment_layouts'
  GT_EGO_MAP_ANTICIPATED:
    MAP_SIZE: 65 # 会自动和 MAPPER map_size 对齐
    MAP_SCALE: 0.05
    HEIGHT_THRESH: [0.2, 1.5]
    MAX_SENSOR_RANGE: 5.05
    NUM_TOPDOWN_MAP_SAMPLE_POINTS: 20000
    GT_TYPE: 'wall_occupancy'
    ALL_MAPS_INFO_PATH: 'data/datasets/exploration/gibson/v1/val/occant_gt_maps/all_maps_info.json'

DATASET:
  TYPE: Exploration-v1
  SPLIT: val
  DATA_PATH: data/datasets/exploration/gibson/v1/{split}/{split}.json.gz
