BASE_TASK_CONFIG_PATH: "configs/exploration/gibson_train.yaml"
TRAINER_NAME: "occant_exp"
ENV_NAME: "ExpRLEnv"
SIMULATOR_GPU_ID: 0
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "trained_models/occant_depth_nig/tb"
VIDEO_DIR: "trained_models/occant_depth_nig/video_dir"
TEST_EPISODE_COUNT: 2
# EVAL_CKPT_PATH_DIR: "trained_models/occant_depth_nig/train_noisy_ep0/checkpoints"
EVAL_CKPT_PATH_DIR: "OccAnt/trained_models/occant_depth_nig/checkpoints"
NUM_PROCESSES: 1
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "trained_models/occant_depth_nig/checkpoints"
NUM_EPISODES: 10000
T_EXP: 1000

RL:
  PPO:
    # ppo params
    ppo_epoch: 4
    num_mini_batch: 1
  ANS:
    reward_type: 'area_seen'
    image_scale_hw: [128, 128]
    MAPPER:
      map_size: 65
      num_mapper_steps: 100
      registration_type: 'moving_average'
      label_id: 'ego_map_gt_anticipated'
      ignore_pose_estimator: False
      pose_predictor_inputs: ['ego_map']
      num_update_batches: 50
      map_batch_size: 150
      use_data_parallel: True
      use_uncer: True
      replay_size: 10000
      gpu_ids: [0]
    OCCUPANCY_ANTICIPATOR:
      type: 'occant_depth_nig'
      GP_ANTICIPATION:
        wall_fov: 120.0
        resnet_type: 'resnet18'
        unet_nsf: 64
    GLOBAL_POLICY:
      use_uncer: True
    LOCAL_POLICY:
      learning_algorithm: 'rl'